let menuList = [
    {
        id: 1,
        typename: '文档大全',
        reid: 0,
        topid: 0,
        sortrank: 4,
        keywords: null,
        description: null,
        icon: null,
        modname: 'document',
    },
    {
        id: 2,
        typename: '首页',
        reid: 0,
        topid: 0,
        sortrank: 1,
        keywords: null,
        description: null,
        icon: null,
        modname: 'dashboard',
    },
    {
        id: 3,
        typename: '异常页',
        reid: 0,
        topid: 0,
        sortrank: 4,
        keywords: null,
        description: null,
        icon: null,
        modname: 'exception',
    },
    {
        id: 4,
        typename: '列表页',
        reid: 0,
        topid: 0,
        sortrank: 4,
        keywords: null,
        description: null,
        icon: null,
        modname: 'list',
    },
    {
        id: 5,
        typename: '表格',
        reid: 0,
        topid: 0,
        sortrank: 4,
        keywords: null,
        description: null,
        icon: null,
        modname: 'table',
    },
    {
        id: 6,
        typename: '分页',
        reid: 0,
        topid: 0,
        sortrank: 4,
        keywords: null,
        description: null,
        icon: null,
        modname: 'page',
    },
    {
        id: 7,
        typename: '基本表单',
        reid: 4,
        topid: 4,
        sortrank: 5,
        keywords: null,
        description: null,
        icon: null,
        modname: 'base',
    },
    {
        id: 8,
        typename: '管理中心',
        reid: 0,
        topid: 0,
        sortrank: 2,
        keywords: null,
        description: null,
        icon: null,
        modname: 'manager',
    },
    {
        id: 9,
        typename: '菜单管理',
        reid: 8,
        topid: 8,
        sortrank: 1,
        keywords: null,
        description: null,
        icon: null,
        modname: 'menuManager',
    },
    {
        id: 10,
        typename: '菜单列表',
        reid: 9,
        topid: 8,
        sortrank: 4,
        keywords: null,
        description: null,
        icon: null,
        modname: 'menuList',
    },
    {
        id: 11,
        typename: '新增菜单',
        reid: 9,
        topid: 8,
        sortrank: 3,
        keywords: null,
        description: null,
        icon: null,
        modname: 'menuAdd',
    },
];

console.log([...['a'], 5]);
let m = ['manager', 'menuManager'];
console.log(m.join("/"));